Repository CouncilDataProject/cdp-backend, pull requests merged in 2021-08, with the labels that each got.

#70 feature/handle-all-ingestion-metadata
  cdp_backend/database/constants.py
  cdp_backend/database/functions.py
  cdp_backend/database/models.py
  cdp_backend/database/validators.py
  cdp_backend/pipeline/event_gather_pipeline.py
  cdp_backend/pipeline/ingestion_models.py
  cdp_backend/pipeline/mock_get_events.py
  cdp_backend/tests/database/test_functions.py
  cdp_backend/tests/database/test_models.py
  cdp_backend/tests/pipeline/test_event_gather_pipeline.py
  setup.py
Labels: enhancement, event gather pipeline

#72 bugfix/matter-status-and-external-source
  cdp_backend/database/functions.py
  cdp_backend/pipeline/event_gather_pipeline.py
  cdp_backend/pipeline/ingestion_models.py
Labels: bug

#73 admin/dep-update-and-pipeline-fixes
  cdp_backend/database/functions.py
  cdp_backend/pipeline/event_gather_pipeline.py
  cdp_backend/utils/file_utils.py
  setup.py
Labels: bug

#74 feature/deterministic-document-keys
  cdp_backend/database/exceptions.py
  cdp_backend/database/functions.py
  cdp_backend/database/models.py
  cdp_backend/database/validators.py
  cdp_backend/pipeline/event_gather_pipeline.py
  cdp_backend/tests/database/test_functions.py
  cdp_backend/tests/database/test_validators.py
Labels: enhancement

#78 Adding thumbnail generation to the pipeline
  cdp_backend/pipeline/event_gather_pipeline.py
  cdp_backend/tests/pipeline/test_event_gather_pipeline.py
Labels: enhancement, event gather pipeline

#83 feature/pass-datetimes-to-get-events-func
  cdp_backend/bin/run_cdp_event_gather.py
  cdp_backend/pipeline/event_gather_pipeline.py
  cdp_backend/pipeline/mock_get_events.py
  cdp_backend/pipeline/pipeline_config.py
Labels: enhancement

#88 bugfix/remove-datetime-weighted-value-from-index-tests
  cdp_backend/tests/pipeline/test_event_index_pipeline.py
Labels: bug
